In [ ]:
import numpy as np
from numpy import dtype

In [ ]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
y = np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
x*y

In [ ]:
# numpy array forces all elements inside it to be of the same type

arr = np.array([1.2, 3, 4, 5])
arr #all the elements here are converted to float

In [ ]:
arr2 = np.array([1.2, 3, 4, 5], dtype = "int32")
arr2 #dtype forces the elements to be in a specific data type

In [ ]:
# makes an array of zeros/ones/any number for the size use the tuple (x,y,z) just put x for 1d array x,y for 2d array and x,y,z for 3d array

z = np.zeros((5,2,6), dtype = "int") 
o = np.ones((3,4,5), dtype = "int")
n = np.full((5,5,5), 99, dtype = "float")
rt = np.full_like(x, 4) #full like will basicall take the shape from another array already created and make it using the number provided here we used the aray shape from the array X from above 

In [ ]:
arr_dimension = arr.ndim  #ndim give the dimnesion of the array
z.ndim

In [ ]:
array_shape = arr.shape
z.shape #give the tuple of the shape of an aaray in (x,y,z)

In [ ]:
z.dtype #gives the type of the data stored

In [ ]:
arr2.itemsize  # Returns the size (in bytes) of each element in the array.
arr2.size  # Returns the total number of elements in the array.
arr2.nbytes # Returns the total number of bytes consumed by the elements of the array.

In [ ]:
arr1 = np.array(
    [
    [1,2,3,5,4,6,3,9,1,2,3,5,1,2,3,5,1,2,3,5],
    [4,6,3,6,1,2,3,5,1,2,3,5,4,6,3,7,1,2,3,5]
]
)
arr1

In [ ]:
# get a specific row
arr1[0,:]
#or
arr1[0]

#get a specific column
arr1[:,1]

In [ ]:
# [startindex:endindex:stepsize]
arr1[0, 1:10:2]

In [ ]:
arr1[0, 3] = 100
arr1

In [ ]:
arr1[0,3] 

In [ ]:
print(arr1)

In [ ]:
arr1[:,2] = 90,67
arr1

In [ ]:
b = np.array([
    [[12,13,14],[15,16,17]]
    ,[[18,19,20],[21,22,23]]
])
b

In [ ]:
b[0, 1, 1] = 90
b

In [ ]:
# random decimal numbers

np.random.rand(4,2)
np.random.random_sample(x.shape)
np.random.randint(77,size = (10,1))

In [ ]:
# identity matrix
np.identity(5)

In [ ]:
arr3 = np.array([[1,2,3]])
r1 = np.repeat(arr3, 3, axis = 0)
r1

In [161]:
# 11111
# 10001
# 10901
# 10001
# 11111

inAr = np.ones((5,5), dtype = "int")
inAr[1:4, 1:4] = 0
inAr[2,2] = 9
print(inAr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [176]:
##### careful when copying arrays

a = np.array([1,2,3])
b = a #this passes the reference for a and doesnt copy so making changes to b will make changes to a alsoinstead use .copy()
b = a.copy()

In [180]:
##### mathematics

# a+2 #adds 2 to all elements
a + 2
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [183]:
before = np.array([[1,2,3,4],[5,6,7,8]])
after = before.reshape(2,2,2)
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [186]:
#vertical stack matrix

np.vstack((before, before))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])